project_name: md2trac

builds:
  - id: linux
    main: ./cmd/md2trac/main.go
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_linux_amd64'

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_linux_checksums.txt"

release:
  draft: false
  prerelease: false
