name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            config: .goreleaser.linux.yaml
          - os: windows-latest
            goos: windows
            config: .goreleaser.windows.yaml
          - os: macos-latest
            goos: darwin
            config: .goreleaser.macos.yaml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.26.2
          args: release --clean --config ${{ matrix.config }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}